name: publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build . --tag ghcr.io/jessseee/actualbudget-importer:latest
          docker run ghcr.io/jessseee/actualbudget-importer:latest
          docker push ghcr.io/jessseee/actualbudget-importer:latest